version: "3.9"

services:
  nextapp:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      NODE_ENV: production
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
