services:
  db:
    image: postgres:14-alpine
    container_name: db_cont
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notesdb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-net

  nextapp:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://user:password@db:5432/notesdb
    depends_on:
      - db
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  db_data:
